# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Extremely fast HTTP Archive (HAR) validator using JSON Schema"
HOMEPAGE="https://github.com/ahmadnassri/har-validator"

LICENSE="ISC"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10"
RDEPEND="${DEPEND}
    =dev-nodejs/chalk-1.1.1
    =dev-nodejs/commander-2.9.0
    =dev-nodejs/is-my-json-valid-2.12.3
    =dev-nodejs/pinkie-promise-2.0.0
"

src_install() {
        npm_src_install

        exeinto "$(get_nodemoduledir)"/bin
        doexe bin/har-validator
        dosym "$(get_nodemoduledir)"/bin/har-validator /usr/bin/har-validator
}
