# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="hardwired configuration loader"
HOMEPAGE="https://github.com/dominictarr/rc#readme"

LICENSE="Complicated"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10"
RDEPEND="${DEPEND}
    >=dev-nodejs/deep-extend-0.4.0
    >=dev-nodejs/ini-1.3.0
    >=dev-nodejs/minimist-1.2.0
    >=dev-nodejs/strip-json-comments-1.0.4
"

src_install() {
        npm_src_install

        exeinto "$(get_nodemoduledir)"/bin
        doexe ./index.js
        dosym "$(get_nodemoduledir)"/./index.js /usr/bin/rc
}
