# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="a little globber"
HOMEPAGE="https://github.com/isaacs/node-glob#readme"

LICENSE="ISC"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10"
RDEPEND="${DEPEND}
    >=dev-nodejs/inflight-1.0.4
    dev-nodejs/inherits
    dev-nodejs/minimatch
    >=dev-nodejs/once-1.3.0
    >=dev-nodejs/path-is-absolute-1.0.0
"
