# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Advanced file system stream things"
HOMEPAGE="https://github.com/isaacs/fstream#readme"

LICENSE="ISC"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10"
RDEPEND="${DEPEND}
    >=dev-nodejs/graceful-fs-4.1.2
    >=dev-nodejs/inherits-2.0.0
    >=dev-nodejs/mkdirp-0.5.0
    ~dev-nodejs/rimraf-2.0.0
"
