# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Fast and simple MD5 hashing utility with zero module dependencies. View MD5 Shootout results, http:&#x2F;&#x2F;jsperf.com&#x2F;md5-shootout&#x2F;39"
HOMEPAGE="https://github.com/trentmillar/md5-o-matic"

LICENSE=""
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10"
RDEPEND="${DEPEND}
"
