# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Temporary file and directory creator"
HOMEPAGE="http://github.com/raszi/node-tmp"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.4.0"
RDEPEND="${DEPEND}
    >=dev-nodejs/os-tmpdir-1.0.1
"
