# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Get the package.json of a package from the npm registry"
HOMEPAGE="https://github.com/sindresorhus/package-json#readme"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10.0"
RDEPEND="${DEPEND}
    >=dev-nodejs/got-5.0.0
    >=dev-nodejs/rc-1.1.2
    >=dev-nodejs/registry-url-3.0.3
    >=dev-nodejs/semver-5.1.0
"
