# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Check if a path is a file, directory, or symlink"
HOMEPAGE="https://github.com/sindresorhus/path-type"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10.0"
RDEPEND="${DEPEND}
    =dev-nodejs/graceful-fs-4.1.2
    =dev-nodejs/pify-2.0.0
    =dev-nodejs/pinkie-promise-2.0.0
"
