# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Provide flexible methods that accept callbacks and return promises without requiring a Promise implementation exist"
HOMEPAGE="https://github.com/jamestalmage/promise-resolver#readme"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.8.0"
RDEPEND="${DEPEND}
    >=dev-nodejs/native-or-bluebird-1.2.0
    ~dev-nodejs/safecb-0.0.1
"
