# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Easily load and save config without having to think about where and how"
HOMEPAGE="https://github.com/yeoman/configstore"

LICENSE="BSD-2-Clause"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10.0"
RDEPEND="${DEPEND}
    =dev-nodejs/graceful-fs-4.1.2
    =dev-nodejs/mkdirp-0.5.0
    =dev-nodejs/object-assign-4.0.1
    =dev-nodejs/os-tmpdir-1.0.0
    =dev-nodejs/osenv-0.1.0
    =dev-nodejs/uuid-2.0.1
    =dev-nodejs/write-file-atomic-1.1.2
    =dev-nodejs/xdg-basedir-2.0.0
"
