# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Light-weight option parsing with an argv hash. No optstrings attached."
HOMEPAGE="https://github.com/bcoe/yargs#readme"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10"
RDEPEND="${DEPEND}
    =dev-nodejs/camelcase-2.0.1
    =dev-nodejs/cliui-3.0.3
    =dev-nodejs/decamelize-1.1.1
    =dev-nodejs/os-locale-1.4.0
    =dev-nodejs/string-width-1.0.1
    =dev-nodejs/window-size-0.1.4
    =dev-nodejs/y18n-3.2.0
"
