# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Returns &#x60;true&#x60; if the given &#x60;string&#x60; or &#x60;array&#x60; ends with &#x60;suffix&#x60; using strict equality for comparisons."
HOMEPAGE="https://github.com/jonschlinkert/ends-with"

LICENSE=""
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10.0"
RDEPEND="${DEPEND}
"
