# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="tar-stream is a streaming tar parser and generator and nothing else. It is streams2 and operates purely using streams which means you can easily extract&#x2F;parse tarballs without ever hitting the file system."
HOMEPAGE="https://github.com/mafintosh/tar-stream"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.8.0"
RDEPEND="${DEPEND}
    >=dev-nodejs/bl-1.0.0
    >=dev-nodejs/end-of-stream-1.0.0
    >=dev-nodejs/readable-stream-2.0.0
    >=dev-nodejs/xtend-4.0.0
"
