# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="quote and parse shell commands"
HOMEPAGE="https://github.com/substack/node-shell-quote"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10"
RDEPEND="${DEPEND}
    >=dev-nodejs/jsonify-0.0.0
    >=dev-nodejs/array-filter-0.0.0
    >=dev-nodejs/array-reduce-0.0.0
    >=dev-nodejs/array-map-0.0.0
"
