# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Turn a writeable and readable stream into a streams2 duplex stream with support for async initialization and streams1&#x2F;streams2 input"
HOMEPAGE="https://github.com/mafintosh/duplexify"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10"
RDEPEND="${DEPEND}
    =dev-nodejs/end-of-stream-1.0.0
    >=dev-nodejs/readable-stream-2.0.0
"
