# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Simplified HTTP request client."
HOMEPAGE="https://github.com/request/request#readme"

LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.8.0"
RDEPEND="${DEPEND}
    >=dev-nodejs/bl-1.0.0
    >=dev-nodejs/caseless-0.11.0
    >=dev-nodejs/extend-3.0.0
    >=dev-nodejs/forever-agent-0.6.1
    >=dev-nodejs/form-data-1.0.0
    >=dev-nodejs/json-stringify-safe-5.0.1
    >=dev-nodejs/mime-types-2.1.7
    >=dev-nodejs/node-uuid-1.4.7
    >=dev-nodejs/qs-5.2.0
    >=dev-nodejs/tunnel-agent-0.4.1
    >=dev-nodejs/tough-cookie-2.2.0
    >=dev-nodejs/http-signature-1.1.0
    >=dev-nodejs/oauth-sign-0.8.0
    >=dev-nodejs/hawk-3.1.0
    >=dev-nodejs/aws-sign2-0.6.0
    >=dev-nodejs/stringstream-0.0.4
    >=dev-nodejs/combined-stream-1.0.5
    >=dev-nodejs/isstream-0.1.2
    >=dev-nodejs/is-typedarray-1.0.0
    >=dev-nodejs/har-validator-2.0.2
"
