# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="parse SPDX license expressions"
HOMEPAGE="https://github.com/kemitchell/spdx-expression-parse.js#readme"

LICENSE="(MIT AND CC-BY-3.0)"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10"
RDEPEND="${DEPEND}
    >=dev-nodejs/spdx-exceptions-1.0.4
    >=dev-nodejs/spdx-license-ids-1.0.0
"
