# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="A library for promises (CommonJS&#x2F;Promises&#x2F;A,B,D)"
HOMEPAGE="https://github.com/kriskowal/q"

LICENSE="[object Object]"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.6.0"
RDEPEND="${DEPEND}
"
