# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="JavaScript parser, mangler&#x2F;compressor and beautifier toolkit"
HOMEPAGE="http://lisperator.net/uglifyjs"

LICENSE="BSD-2-Clause"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.8.0"
RDEPEND="${DEPEND}
    >=dev-nodejs/async-0.2.6
    >=dev-nodejs/source-map-0.5.1
    >=dev-nodejs/uglify-to-browserify-1.0.0
    >=dev-nodejs/yargs-3.10.0
"

src_install() {
        npm_src_install

        exeinto "$(get_nodemoduledir)"/bin
        doexe bin/uglifyjs
        dosym "$(get_nodemoduledir)"/bin/uglifyjs /usr/bin/uglifyjs
}
