# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Utility method to run function either synchronously or asynchronously using the common &#x60;this.async()&#x60; style."
HOMEPAGE="https://github.com/SBoudrias/run-async"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10"
RDEPEND="${DEPEND}
    >=dev-nodejs/is-promise-2.1.0
    >=dev-nodejs/once-1.3.0
    >=dev-nodejs/promise-resolver-1.0.0
"
