# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Recursively mkdir, like &#x60;mkdir -p&#x60;"
HOMEPAGE="https://github.com/substack/node-mkdirp#readme"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10"
RDEPEND="${DEPEND}
    =dev-nodejs/minimist-0.0.8
"

src_install() {
        npm_src_install

        exeinto "$(get_nodemoduledir)"/bin
        doexe bin/cmd.js
        dosym "$(get_nodemoduledir)"/bin/cmd.js /usr/bin/mkdirp
}
