# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Normalizes data that can be found in package.json files."
HOMEPAGE="https://github.com/npm/normalize-package-data#readme"

LICENSE="BSD-2-Clause"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10"
RDEPEND="${DEPEND}
    >=dev-nodejs/hosted-git-info-2.1.4
    >=dev-nodejs/is-builtin-module-1.0.0
    =dev-nodejs/semver-2*
    >=dev-nodejs/validate-npm-package-license-3.0.1
"
