# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Reference implementation of Joyent's HTTP Signature scheme."
HOMEPAGE="https://github.com/joyent/node-http-signature/"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10"
RDEPEND="${DEPEND}
    >=dev-nodejs/assert-plus-0.1.5
    >=dev-nodejs/jsprim-1.2.2
    >=dev-nodejs/sshpk-1.7.0
"
