# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="A collection of common interactive command line user interfaces."
HOMEPAGE="https://github.com/sboudrias/Inquirer.js#readme"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10"
RDEPEND="${DEPEND}
    >=dev-nodejs/ansi-escapes-1.1.0
    >=dev-nodejs/ansi-regex-2.0.0
    >=dev-nodejs/chalk-1.0.0
    >=dev-nodejs/cli-cursor-1.0.1
    >=dev-nodejs/cli-width-1.0.1
    >=dev-nodejs/figures-1.3.5
    >=dev-nodejs/lodash-3.3.1
    >=dev-nodejs/readline2-1.0.1
    >=dev-nodejs/run-async-0.1.0
    >=dev-nodejs/rx-lite-3.1.2
    >=dev-nodejs/strip-ansi-3.0.0
    >=dev-nodejs/through-2.3.6
"
