# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Handlebars provides the power necessary to let you build semantic templates effectively with no frustration"
HOMEPAGE="http://www.handlebarsjs.com/"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.4.7"
RDEPEND="${DEPEND}
    >=dev-nodejs/async-1.4.0
    >=dev-nodejs/optimist-0.6.1
    >=dev-nodejs/source-map-0.4.4
    =dev-nodejs/uglify-js-2.6*
"

src_install() {
        npm_src_install

        exeinto "$(get_nodemoduledir)"/bin
        doexe bin/handlebars
        dosym "$(get_nodemoduledir)"/bin/handlebars /usr/bin/handlebars
}
