# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="A library for finding and using SSH public keys"
HOMEPAGE="https://github.com/arekinath/node-sshpk#readme"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.8.0"
RDEPEND="${DEPEND}
    >=dev-nodejs/asn1-0.2.3
    >=dev-nodejs/assert-plus-0.2.0
    >=dev-nodejs/dashdash-1.10.1
    >=dev-nodejs/jsbn-0.1.0
    >=dev-nodejs/tweetnacl-0.13.0
    >=dev-nodejs/jodid25519-1.0.0
    >=dev-nodejs/ecc-jsbn-0.0.1
"

src_install() {
        npm_src_install

        exeinto "$(get_nodemoduledir)"/bin
        doexe bin/sshpk-conv
        dosym "$(get_nodemoduledir)"/bin/sshpk-conv /usr/bin/sshpk-conv
}
