# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="A comprehensive library for mime-type mapping"
HOMEPAGE="https://github.com/broofa/node-mime"

LICENSE=""
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10"
RDEPEND="${DEPEND}
"

src_install() {
        npm_src_install

        exeinto "$(get_nodemoduledir)"/bin
        doexe cli.js
        dosym "$(get_nodemoduledir)"/cli.js /usr/bin/mime
}
