# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Like `fs.createWriteStream(...)`, but atomic."
HOMEPAGE="https://github.com/npm/fs-write-stream-atomic"

LICENSE="ISC"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10"
RDEPEND="${DEPEND}
    >=dev-nodejs/graceful-fs-4.1.2
    >=dev-nodejs/iferr-0.1.5
    >=dev-nodejs/imurmurhash-0.1.4
    =dev-nodejs/readable-stream-1*
"
