# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Simplified HTTP/HTTPS requests"
HOMEPAGE="https://github.com/sindresorhus/got"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10.0"
RDEPEND="${DEPEND}
    >=dev-nodejs/create-error-class-2.0.0
    >=dev-nodejs/duplexify-3.2.0
    >=dev-nodejs/is-plain-obj-1.0.0
    >=dev-nodejs/is-redirect-1.0.0
    >=dev-nodejs/is-stream-1.0.0
    >=dev-nodejs/lowercase-keys-1.0.0
    >=dev-nodejs/node-status-codes-1.0.0
    >=dev-nodejs/object-assign-4.0.1
    >=dev-nodejs/parse-json-2.1.0
    >=dev-nodejs/pinkie-promise-2.0.0
    >=dev-nodejs/read-all-stream-3.0.0
    >=dev-nodejs/timed-out-2.0.0
    >=dev-nodejs/unzip-response-1.0.0
    >=dev-nodejs/url-parse-lax-1.0.0
"
