# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="easily create complex multi-column command-line-interfaces"
HOMEPAGE="https://github.com/bcoe/cliui"

LICENSE="ISC"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10"
RDEPEND="${DEPEND}
    =dev-nodejs/string-width-1.0.1
    =dev-nodejs/strip-ansi-3.0.0
    =dev-nodejs/wrap-ansi-1.0.0
"
