# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="A library to create readable &quot;multipart&#x2F;form-data&quot; streams. Can be used to submit forms and file uploads to other web applications."
HOMEPAGE="https://github.com/form-data/form-data#readme"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10"
RDEPEND="${DEPEND}
    =dev-nodejs/async-1.4.0
    =dev-nodejs/combined-stream-1.0.5
    =dev-nodejs/mime-types-2.1.3
"
