# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# Initially this file was autogenerated by [npm2ebuild](https://github.com/zaufi/npm2ebuild)
#

EAPI=5

inherit npm

DESCRIPTION="Read a package.json file"
HOMEPAGE="https://github.com/sindresorhus/read-pkg"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
DEPEND=">=net-libs/nodejs-0.10.0"
RDEPEND="${DEPEND}
    =dev-nodejs/load-json-file-1.0.0
    =dev-nodejs/normalize-package-data-2.3.2
    =dev-nodejs/path-type-1.0.0
"
